# default profile, 与环境无关
spring:
  profiles:
    active: dev
  application:
    name: ctg-mes-config

jasypt:
  encryptor:
    password: ctg_mes
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
